# Generated by Django 5.2.12 on 2026-04-09 12:00

import listings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_property_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=listings.models.city_image_path),
        ),
        migrations.AlterField(
            model_name='property',
            name='main_image',
            field=models.ImageField(upload_to=listings.models.property_main_image_path),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(upload_to=listings.models.property_gallery_image_path),
        ),
        migrations.AlterField(
            model_name='university',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=listings.models.university_logo_path),
        ),
    ]
